name: React Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker secrets
        run: |
          if [ -z "${DOCKER_USERNAME}" ]; then
            echo "ERROR: DOCKER_USERNAME secret is missing"
            exit 1
          fi
          if [ -z "${DOCKER_PASSWORD}" ]; then
            echo "ERROR: DOCKER_PASSWORD secret is missing"
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/react-frontend-app:latest
            ${{ env.DOCKER_USERNAME }}/react-frontend-app:${{ github.run_number }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/react-frontend-app:cache
          cache-to: type=inline

      - name: Confirm successful push
        run: echo "✅ Docker image pushed to Docker Hub successfull!"