name: React Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx (for cross-platform builds & caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build and Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/react-frontend-app:latest
            ${{ secrets.DOCKER_USERNAME }}/react-frontend-app:${{ github.run_number }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/react-frontend-app:cache
          cache-to: type=inline

      # 5️⃣ (Optional) Post-deployment confirmation
      - name: Confirm successful push
        run: echo "✅ Docker image pushed to Docker Hub successfully!"
